name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Debug Variables
        run: |
          echo "Checking Repository Variables:"
          echo "777777777 vars: ${{ vars }}"
          echo "REMOTE_HOST: ${{ vars.REMOTE_HOST }}"
          echo "REMOTE_USER: ${{ vars.REMOTE_USER }}"
          echo "TARGET: ${{ vars.TARGET }}"
          echo "SSH_PRIVATE_KEY: ${{ vars.SSH_PRIVATE_KEY }}"
          
          echo "Checking Repository Secrets:"
          echo "777777777 Secrets: ${{ secrets }}"
          echo "777777777 REMOTE_HOST: ${{ secrets.REMOTE_HOST }}"
          echo "REMOTE_USER: ${{ secrets.REMOTE_USER }}"
          echo "TARGET: ${{ secrets.TARGET }}"
          echo "SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}"

      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@v4.1.10
        env:
          SSH_PRIVATE_KEY: ${{ vars.SSH_PRIVATE_KEY }}
          ARGS: '-avzr --delete'
          SOURCE: 'build'
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          TARGET: ${{ vars.TARGET }}
